// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("bed_information")]
    public partial class BedInformation
    {
        [Key]
        [Column("bedinfor_id")]
        public int BedinforId { get; set; }
        [Key]
        [Column("bedinfor_size")]
        [Precision(2, 1)]
        public decimal BedinforSize { get; set; }
        [Column("bedinfor_no_beds")]
        public short BedinforNoBeds { get; set; }

        [JsonIgnore]
		[ForeignKey("BedinforId")]
        [InverseProperty("BedInformations")]
        public virtual Roomtype Bedinfor { get; set; }
    }
}