// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("booking_reservation")]
    public partial class BookingReservation
    {
        public BookingReservation()
        {
            Invoices = new HashSet<Invoice>();
            RentalRooms = new HashSet<RentalRoom>();
        }

        [Key]
        [Column("booking_id")]
        [StringLength(16)]
        public string BookingId { get; set; }
        [Column("booking_datetime", TypeName = "timestamp without time zone")]
        public DateTime? BookingDatetime { get; set; }
        [Column("checkin_date")]
        public DateOnly? CheckinDate { get; set; }
        [Column("number_of_guests")]
        public short NumberOfGuests { get; set; }
        [Column("checkout_date")]
        public DateOnly? CheckoutDate { get; set; }
        [Column("status")]
        public short Status { get; set; }
        [Column("total_price")]
        public short TotalPrice { get; set; }
        [Required]
        [Column("customer_id")]
        [StringLength(8)]
        public string CustomerId { get; set; }
        [Required]
        [Column("package_name")]
        [StringLength(50)]
        public string PackageName { get; set; }

        [JsonIgnore]
		[ForeignKey("CustomerId")]
        [InverseProperty("BookingReservations")]
        public virtual Customer Customer { get; set; }
        [JsonIgnore]
		[ForeignKey("PackageName")]
        [InverseProperty("BookingReservations")]
        public virtual ServicePackage PackageNameNavigation { get; set; }
        [JsonIgnore]
		[InverseProperty("Booking")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [JsonIgnore]
		[InverseProperty("Booking")]
        public virtual ICollection<RentalRoom> RentalRooms { get; set; }
    }
}