// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("branch_image")]
    public partial class BranchImage
    {
        [Key]
        [Column("branchimg")]
        [StringLength(200)]
        public string Branchimg { get; set; }
        [Key]
        [Column("branchimg_id")]
        public int BranchimgId { get; set; }

        [ForeignKey("BranchimgId")]
        [InverseProperty("BranchImages")]
        public virtual Branch BranchimgNavigation { get; set; }
    }
}