// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("branch_with_roomtypes")]
    public partial class BranchWithRoomtype
    {
        [Key]
        [Column("bedinfor_roomtypes_id")]
        public int BedinforRoomtypesId { get; set; }
        [Key]
        [Column("bedinfor_branches_id")]
        public int BedinforBranchesId { get; set; }
        [Column("branch_with_roomtypes_rent_price")]
        public short BranchWithRoomtypesRentPrice { get; set; }

        [ForeignKey("BedinforBranchesId")]
        [InverseProperty("BranchWithRoomtypes")]
        public virtual Branch BedinforBranches { get; set; }
        [ForeignKey("BedinforRoomtypesId")]
        [InverseProperty("BranchWithRoomtypes")]
        public virtual Roomtype BedinforRoomtypes { get; set; }
    }
}