// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("business_premise")]
    [Index("BranchId", Name = "business_premise_branch_id_key", IsUnique = true)]
    public partial class BusinessPremise
    {
        public BusinessPremise()
        {
            PremiseImages = new HashSet<PremiseImage>();
            PremiseOperationTimes = new HashSet<PremiseOperationTime>();
        }

        [Key]
        [Column("branch_id")]
        public int BranchId { get; set; }
        [Key]
        [Column("premise_order")]
        public short PremiseOrder { get; set; }
        [Column("rental_price")]
        public short RentalPrice { get; set; }
        [Column("premise_width")]
        public short PremiseWidth { get; set; }
        [Column("premise_length")]
        public short PremiseLength { get; set; }
        [Column("description")]
        [StringLength(100)]
        public string Description { get; set; }
        [Required]
        [Column("service_id")]
        [StringLength(6)]
        public string ServiceId { get; set; }
        [Column("premise_name")]
        [StringLength(50)]
        public string PremiseName { get; set; }

        [ForeignKey("ServiceId")]
        [InverseProperty("BusinessPremises")]
        public virtual Service Service { get; set; }
        [InverseProperty("BusinessPremise")]
        public virtual ICollection<PremiseImage> PremiseImages { get; set; }
        [InverseProperty("BusinessPremise")]
        public virtual ICollection<PremiseOperationTime> PremiseOperationTimes { get; set; }
    }
}