// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("customer")]
    [Index("CustomerCccdCmnd", Name = "customer_customer_cccd_cmnd_key", IsUnique = true)]
    [Index("CustomerEmail", Name = "customer_customer_email_key", IsUnique = true)]
    [Index("CustomerTelephone", Name = "customer_customer_telephone_key", IsUnique = true)]
    [Index("CustomerUsername", Name = "customer_customer_username_key", IsUnique = true)]
    public partial class Customer
    {
        public Customer()
        {
            BookingReservations = new HashSet<BookingReservation>();
            ServicePackageInvoices = new HashSet<ServicePackageInvoice>();
        }

        [Key]
        [Column("customer_id")]
        [StringLength(8)]
        public string CustomerId { get; set; }
        [Required]
        [Column("customer_cccd_cmnd")]
        [StringLength(12)]
        public string CustomerCccdCmnd { get; set; }
        [Required]
        [Column("customer_fullname")]
        [StringLength(50)]
        public string CustomerFullname { get; set; }
        [Required]
        [Column("customer_telephone")]
        [StringLength(11)]
        public string CustomerTelephone { get; set; }
        [Required]
        [Column("customer_email")]
        [StringLength(100)]
        public string CustomerEmail { get; set; }
        [Required]
        [Column("customer_username")]
        [StringLength(50)]
        public string CustomerUsername { get; set; }
        [Required]
        [Column("customer_password")]
        [StringLength(100)]
        public string CustomerPassword { get; set; }
        [Column("customer_score")]
        public short CustomerScore { get; set; }
        [Column("customer_type")]
        public short CustomerType { get; set; }

        [InverseProperty("Customer")]
        public virtual ICollection<BookingReservation> BookingReservations { get; set; }
        [JsonIgnore]
		[InverseProperty("Customer")]
        public virtual ICollection<ServicePackageInvoice> ServicePackageInvoices { get; set; }
    }
}