// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("enterprise")]
    public partial class Enterprise
    {
        public Enterprise()
        {
            Services = new HashSet<Service>();
        }

        [Key]
        [Column("enterprise_id")]
        [StringLength(6)]
        public string EnterpriseId { get; set; }
        [Column("enterprise_name")]
        [StringLength(50)]
        public string EnterpriseName { get; set; }

        [InverseProperty("Enterprise")]
        public virtual ICollection<Service> Services { get; set; }
    }
}