// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("premise_operation_time")]
    public partial class PremiseOperationTime
    {
        [Key]
        [Column("branch_id")]
        public int BranchId { get; set; }
        [Key]
        [Column("premise_order")]
        public short PremiseOrder { get; set; }
        [Key]
        [Column("start_time")]
        public TimeOnly StartTime { get; set; }
        [Column("end_time")]
        public TimeOnly? EndTime { get; set; }

        [ForeignKey("BranchId,PremiseOrder")]
        [InverseProperty("PremiseOperationTimes")]
        public virtual BusinessPremise BusinessPremise { get; set; }
    }
}