// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("premise_image")]
    [Index("BranchId", Name = "premise_image_branch_id_key", IsUnique = true)]
    public partial class PremiseImage
    {
        [Key]
        [Column("branch_id")]
        public int BranchId { get; set; }
        [Key]
        [Column("premise_order")]
        public short PremiseOrder { get; set; }
        [Key]
        [Column("premise_logo")]
        [StringLength(200)]
        public string PremiseLogo { get; set; }

        [ForeignKey("BranchId,PremiseOrder")]
        [InverseProperty("PremiseImages")]
        public virtual BusinessPremise BusinessPremise { get; set; }
    }
}