// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("rental_room")]
    public partial class RentalRoom
    {
        [Key]
        [Column("booking_id")]
        [StringLength(16)]
        public string BookingId { get; set; }
        [Key]
        [Column("room_branch_id")]
        public int RoomBranchId { get; set; }
        [Key]
        [Column("room_number")]
        [StringLength(3)]
        public string RoomNumber { get; set; }

        [ForeignKey("BookingId")]
        [InverseProperty("RentalRooms")]
        public virtual BookingReservation Booking { get; set; }
    }
}