// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("room")]
    public partial class Room
    {
        public Room()
        {
            Supplies = new HashSet<Supply>();
        }

        [Key]
        [Column("room_branch_id")]
        public int RoomBranchId { get; set; }
        [Key]
        [Column("room_number")]
        [StringLength(3)]
        public string RoomNumber { get; set; }
        [Required]
        [Column("room_area_name")]
        [StringLength(100)]
        public string RoomAreaName { get; set; }
        [Column("room_roomtypes_id")]
        public int RoomRoomtypesId { get; set; }

        [ForeignKey("RoomBranchId")]
        [InverseProperty("Rooms")]
        public virtual Branch RoomBranch { get; set; }
        [ForeignKey("RoomRoomtypesId")]
        [InverseProperty("Rooms")]
        public virtual Roomtype RoomRoomtypes { get; set; }
        [InverseProperty("Supplies")]
        public virtual ICollection<Supply> Supplies { get; set; }
    }
}