// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("room_supplies")]
    public partial class RoomSupply
    {
        [Key]
        [Column("room_supplies_id")]
        [StringLength(6)]
        public string RoomSuppliesId { get; set; }
        [Key]
        [Column("room_supplies_room_id")]
        public int RoomSuppliesRoomId { get; set; }
        [Column("room_supplies_number")]
        public short RoomSuppliesNumber { get; set; }

        [ForeignKey("RoomSuppliesId")]
        [InverseProperty("RoomSupplies")]
        public virtual SuppliesType RoomSupplies { get; set; }
        [ForeignKey("RoomSuppliesRoomId")]
        [InverseProperty("RoomSupplies")]
        public virtual Roomtype RoomSuppliesRoom { get; set; }
    }
}