// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("roomtype")]
    public partial class Roomtype
    {
        public Roomtype()
        {
            BedInformations = new HashSet<BedInformation>();
            BranchWithRoomtypes = new HashSet<BranchWithRoomtype>();
            RoomSupplies = new HashSet<RoomSupply>();
            Rooms = new HashSet<Room>();
        }

        [Key]
        [Column("roomtype_id")]
        public int RoomtypeId { get; set; }
        [Required]
        [Column("roomtype_name")]
        [StringLength(50)]
        public string RoomtypeName { get; set; }
        [Required]
        [Column("roomtype_area")]
        [StringLength(10)]
        public string RoomtypeArea { get; set; }
        [Required]
        [Column("roomtype_description")]
        [StringLength(300)]
        public string RoomtypeDescription { get; set; }
        [Column("roomtype_no_guests")]
        public short RoomtypeNoGuests { get; set; }

        [InverseProperty("Bedinfor")]
        public virtual ICollection<BedInformation> BedInformations { get; set; }
        [JsonIgnore]
		[InverseProperty("BedinforRoomtypes")]
        public virtual ICollection<BranchWithRoomtype> BranchWithRoomtypes { get; set; }
        [JsonIgnore]
		[InverseProperty("RoomSuppliesRoom")]
        public virtual ICollection<RoomSupply> RoomSupplies { get; set; }
        [JsonIgnore]
		[InverseProperty("RoomRoomtypes")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}