// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("service_package_invoice")]
    public partial class ServicePackageInvoice
    {
        [Key]
        [Column("customer_id")]
        [StringLength(8)]
        public string CustomerId { get; set; }
        [Key]
        [Column("package_name")]
        [StringLength(50)]
        public string PackageName { get; set; }
        [Key]
        [Column("buying_datetime", TypeName = "timestamp without time zone")]
        public DateTime BuyingDatetime { get; set; }
        [Column("start_date")]
        public DateOnly? StartDate { get; set; }
        [Column("total_price")]
        public short TotalPrice { get; set; }

        [ForeignKey("CustomerId")]
        [InverseProperty("ServicePackageInvoices")]
        public virtual Customer Customer { get; set; }
        [ForeignKey("PackageName")]
        [InverseProperty("ServicePackageInvoices")]
        public virtual ServicePackage PackageNameNavigation { get; set; }
    }
}