// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("service_package")]
    public partial class ServicePackage
    {
        public ServicePackage()
        {
            BookingReservations = new HashSet<BookingReservation>();
            ServicePackageInvoices = new HashSet<ServicePackageInvoice>();
        }

        [Key]
        [Column("package_name")]
        [StringLength(50)]
        public string PackageName { get; set; }
        [Column("package_days")]
        public short PackageDays { get; set; }
        [Column("package_customers")]
        public short PackageCustomers { get; set; }
        [Column("package_price")]
        public short PackagePrice { get; set; }

        [InverseProperty("PackageNameNavigation")]
        public virtual ICollection<BookingReservation> BookingReservations { get; set; }
        [InverseProperty("PackageNameNavigation")]
        public virtual ICollection<ServicePackageInvoice> ServicePackageInvoices { get; set; }
    }
}