// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("supplies")]
    public partial class Supply
    {
        [Key]
        [Column("supplies_branch")]
        public int SuppliesBranch { get; set; }
        [Key]
        [Column("supplies_types_id1")]
        [StringLength(6)]
        public string SuppliesTypesId1 { get; set; }
        [Key]
        [Column("supplies_number")]
        public int SuppliesNumber { get; set; }
        [Column("supplies_status")]
        [StringLength(100)]
        public string SuppliesStatus { get; set; }
        [Required]
        [Column("supplies_room_number")]
        [StringLength(3)]
        public string SuppliesRoomNumber { get; set; }

        [ForeignKey("SuppliesRoomNumber,SuppliesBranch")]
        [InverseProperty("Supplies")]
        public virtual Room Supplies { get; set; }
        [ForeignKey("SuppliesBranch")]
        [InverseProperty("Supplies")]
        public virtual Branch SuppliesBranchNavigation { get; set; }
        [ForeignKey("SuppliesTypesId1")]
        [InverseProperty("Supplies")]
        public virtual SuppliesType SuppliesTypesId1Navigation { get; set; }
    }
}