// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("supplying")]
    public partial class Supplying
    {
        [Required]
        [Column("supplying_by_suppliers")]
        [StringLength(7)]
        public string SupplyingBySuppliers { get; set; }
        [Key]
        [Column("supplying_supplyies_id")]
        [StringLength(6)]
        public string SupplyingSupplyiesId { get; set; }
        [Key]
        [Column("supplying_branch")]
        public int SupplyingBranch { get; set; }

        [ForeignKey("SupplyingBranch")]
        [InverseProperty("Supplyings")]
        public virtual Branch SupplyingBranchNavigation { get; set; }
        [ForeignKey("SupplyingBySuppliers")]
        [InverseProperty("Supplyings")]
        public virtual Supplier SupplyingBySuppliersNavigation { get; set; }
        [ForeignKey("SupplyingSupplyiesId")]
        [InverseProperty("Supplyings")]
        public virtual SuppliesType SupplyingSupplyies { get; set; }
    }
}