// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("suppliers")]
    public partial class Supplier
    {
        public Supplier()
        {
            Supplyings = new HashSet<Supplying>();
        }

        [Key]
        [Column("suppliers_id")]
        [StringLength(7)]
        public string SuppliersId { get; set; }
        [Required]
        [Column("suppliers_name")]
        [StringLength(50)]
        public string SuppliersName { get; set; }
        [Required]
        [Column("suppliers_email")]
        [StringLength(100)]
        public string SuppliersEmail { get; set; }
        [Required]
        [Column("suppliers_address")]
        [StringLength(200)]
        public string SuppliersAddress { get; set; }

        [InverseProperty("SupplyingBySuppliersNavigation")]
        public virtual ICollection<Supplying> Supplyings { get; set; }
    }
}