// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CMS_Resort.Models
{
    [Table("supplies_types")]
    public partial class SuppliesType
    {
        public SuppliesType()
        {
            RoomSupplies = new HashSet<RoomSupply>();
            Supplies = new HashSet<Supply>();
            Supplyings = new HashSet<Supplying>();
        }

        [Key]
        [Column("supplies_types_id")]
        [StringLength(6)]
        public string SuppliesTypesId { get; set; }
        [Required]
        [Column("supplies_types_name")]
        [StringLength(50)]
        public string SuppliesTypesName { get; set; }

        [InverseProperty("RoomSupplies")]
        public virtual ICollection<RoomSupply> RoomSupplies { get; set; }
        [InverseProperty("SuppliesTypesId1Navigation")]
        public virtual ICollection<Supply> Supplies { get; set; }
        [InverseProperty("SupplyingSupplyies")]
        public virtual ICollection<Supplying> Supplyings { get; set; }
    }
}